name: LifeShare
version: 1.1
main: x0derek.lifeShare.LifeShare
authors:
  - x0derek
api-version: 1.21
commands:
  lifeshare:
    description: Main LifeShare command
    usage: /<command> <invite|accept|deny>
    aliases: [ls]